//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sisyphus.itws {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="itwts_TrelloSyncSoapBinding", Namespace="http://itworks24.ru/sisyphus/trellosync")]
    public partial class itwts_TrelloSync : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddCardHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetСontractorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNomenclatureOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetContractorsBoardsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetContractorBoardOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public itwts_TrelloSync() {
            this.Url = global::Sisyphus.Properties.Settings.Default.TrelloChecker_itws_itwts_TrelloSync;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddCardHistoryCompletedEventHandler AddCardHistoryCompleted;
        
        /// <remarks/>
        public event GetСontractorsCompletedEventHandler GetСontractorsCompleted;
        
        /// <remarks/>
        public event GetNomenclatureCompletedEventHandler GetNomenclatureCompleted;
        
        /// <remarks/>
        public event SetContractorsBoardsCompletedEventHandler SetContractorsBoardsCompleted;
        
        /// <remarks/>
        public event SetContractorBoardCompletedEventHandler SetContractorBoardCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itworks24.ru/sisyphus/trellosync#itwts_TrelloSync:AddCardHistory", RequestNamespace="http://itworks24.ru/sisyphus/trellosync", ResponseNamespace="http://itworks24.ru/sisyphus/trellosync", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool AddCardHistory(CardHistory CardHistory, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string ErrorRepresent) {
            object[] results = this.Invoke("AddCardHistory", new object[] {
                        CardHistory,
                        ErrorRepresent});
            ErrorRepresent = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddCardHistoryAsync(CardHistory CardHistory, string ErrorRepresent) {
            this.AddCardHistoryAsync(CardHistory, ErrorRepresent, null);
        }
        
        /// <remarks/>
        public void AddCardHistoryAsync(CardHistory CardHistory, string ErrorRepresent, object userState) {
            if ((this.AddCardHistoryOperationCompleted == null)) {
                this.AddCardHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCardHistoryOperationCompleted);
            }
            this.InvokeAsync("AddCardHistory", new object[] {
                        CardHistory,
                        ErrorRepresent}, this.AddCardHistoryOperationCompleted, userState);
        }
        
        private void OnAddCardHistoryOperationCompleted(object arg) {
            if ((this.AddCardHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCardHistoryCompleted(this, new AddCardHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itworks24.ru/sisyphus/trellosync#itwts_TrelloSync:GetСontractors", RequestNamespace="http://itworks24.ru/sisyphus/trellosync", ResponseNamespace="http://itworks24.ru/sisyphus/trellosync", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ContractorList")]
        public Contractor[] GetСontractors([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string ErrorRepresent) {
            object[] results = this.Invoke("GetСontractors", new object[] {
                        ErrorRepresent});
            ErrorRepresent = ((string)(results[1]));
            return ((Contractor[])(results[0]));
        }
        
        /// <remarks/>
        public void GetСontractorsAsync(string ErrorRepresent) {
            this.GetСontractorsAsync(ErrorRepresent, null);
        }
        
        /// <remarks/>
        public void GetСontractorsAsync(string ErrorRepresent, object userState) {
            if ((this.GetСontractorsOperationCompleted == null)) {
                this.GetСontractorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetСontractorsOperationCompleted);
            }
            this.InvokeAsync("GetСontractors", new object[] {
                        ErrorRepresent}, this.GetСontractorsOperationCompleted, userState);
        }
        
        private void OnGetСontractorsOperationCompleted(object arg) {
            if ((this.GetСontractorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetСontractorsCompleted(this, new GetСontractorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itworks24.ru/sisyphus/trellosync#itwts_TrelloSync:GetNomenclature", RequestNamespace="http://itworks24.ru/sisyphus/trellosync", ResponseNamespace="http://itworks24.ru/sisyphus/trellosync", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return", IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("NomencletureList")]
        public Nomenclature[] GetNomenclature([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string ErrorRepresent) {
            object[] results = this.Invoke("GetNomenclature", new object[] {
                        ErrorRepresent});
            ErrorRepresent = ((string)(results[1]));
            return ((Nomenclature[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNomenclatureAsync(string ErrorRepresent) {
            this.GetNomenclatureAsync(ErrorRepresent, null);
        }
        
        /// <remarks/>
        public void GetNomenclatureAsync(string ErrorRepresent, object userState) {
            if ((this.GetNomenclatureOperationCompleted == null)) {
                this.GetNomenclatureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNomenclatureOperationCompleted);
            }
            this.InvokeAsync("GetNomenclature", new object[] {
                        ErrorRepresent}, this.GetNomenclatureOperationCompleted, userState);
        }
        
        private void OnGetNomenclatureOperationCompleted(object arg) {
            if ((this.GetNomenclatureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNomenclatureCompleted(this, new GetNomenclatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itworks24.ru/sisyphus/trellosync#itwts_TrelloSync:SetContractorsBoards", RequestNamespace="http://itworks24.ru/sisyphus/trellosync", ResponseNamespace="http://itworks24.ru/sisyphus/trellosync", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool SetContractorsBoards([System.Xml.Serialization.XmlArrayItemAttribute("ContractorList")] Contractor[] FilledContractorList, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string ErrorRepresent) {
            object[] results = this.Invoke("SetContractorsBoards", new object[] {
                        FilledContractorList,
                        ErrorRepresent});
            ErrorRepresent = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetContractorsBoardsAsync(Contractor[] FilledContractorList, string ErrorRepresent) {
            this.SetContractorsBoardsAsync(FilledContractorList, ErrorRepresent, null);
        }
        
        /// <remarks/>
        public void SetContractorsBoardsAsync(Contractor[] FilledContractorList, string ErrorRepresent, object userState) {
            if ((this.SetContractorsBoardsOperationCompleted == null)) {
                this.SetContractorsBoardsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetContractorsBoardsOperationCompleted);
            }
            this.InvokeAsync("SetContractorsBoards", new object[] {
                        FilledContractorList,
                        ErrorRepresent}, this.SetContractorsBoardsOperationCompleted, userState);
        }
        
        private void OnSetContractorsBoardsOperationCompleted(object arg) {
            if ((this.SetContractorsBoardsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetContractorsBoardsCompleted(this, new SetContractorsBoardsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://itworks24.ru/sisyphus/trellosync#itwts_TrelloSync:SetContractorBoard", RequestNamespace="http://itworks24.ru/sisyphus/trellosync", ResponseNamespace="http://itworks24.ru/sisyphus/trellosync", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public bool SetContractorBoard(Contractor Contractor, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ref string ErrorRepresent) {
            object[] results = this.Invoke("SetContractorBoard", new object[] {
                        Contractor,
                        ErrorRepresent});
            ErrorRepresent = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SetContractorBoardAsync(Contractor Contractor, string ErrorRepresent) {
            this.SetContractorBoardAsync(Contractor, ErrorRepresent, null);
        }
        
        /// <remarks/>
        public void SetContractorBoardAsync(Contractor Contractor, string ErrorRepresent, object userState) {
            if ((this.SetContractorBoardOperationCompleted == null)) {
                this.SetContractorBoardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetContractorBoardOperationCompleted);
            }
            this.InvokeAsync("SetContractorBoard", new object[] {
                        Contractor,
                        ErrorRepresent}, this.SetContractorBoardOperationCompleted, userState);
        }
        
        private void OnSetContractorBoardOperationCompleted(object arg) {
            if ((this.SetContractorBoardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetContractorBoardCompleted(this, new SetContractorBoardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itworks24.ru/sisyphus/trellosync")]
    public partial class CardHistory {
        
        private string creatorIdField;
        
        private string creatorUserNameField;
        
        private string creatorEMailField;
        
        private CardRecord[] inWorkActionRecordListField;
        
        private string[] labelsField;
        
        private string cardIdField;
        
        private string boardIdField;
        
        private Comment[] commentsField;
        
        private System.Nullable<System.DateTime> creationDateTimeField;
        
        private string textField;
        
        private string nameField;
        
        private string cardUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CreatorId {
            get {
                return this.creatorIdField;
            }
            set {
                this.creatorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CreatorUserName {
            get {
                return this.creatorUserNameField;
            }
            set {
                this.creatorUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CreatorEMail {
            get {
                return this.creatorEMailField;
            }
            set {
                this.creatorEMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InWorkActionRecordList", IsNullable=true)]
        public CardRecord[] InWorkActionRecordList {
            get {
                return this.inWorkActionRecordListField;
            }
            set {
                this.inWorkActionRecordListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Labels")]
        public string[] Labels {
            get {
                return this.labelsField;
            }
            set {
                this.labelsField = value;
            }
        }
        
        /// <remarks/>
        public string CardId {
            get {
                return this.cardIdField;
            }
            set {
                this.cardIdField = value;
            }
        }
        
        /// <remarks/>
        public string BoardId {
            get {
                return this.boardIdField;
            }
            set {
                this.boardIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Comments")]
        public Comment[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreationDateTime {
            get {
                return this.creationDateTimeField;
            }
            set {
                this.creationDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string CardUrl {
            get {
                return this.cardUrlField;
            }
            set {
                this.cardUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itworks24.ru/sisyphus/trellosync")]
    public partial class CardRecord {
        
        private System.DateTime startDateTimeField;
        
        private System.DateTime finishDateTimeField;
        
        private string beginerIdField;
        
        private string beginerUserNameField;
        
        private string beginerEMailField;
        
        private string finisherIdField;
        
        private string finisherEMailField;
        
        private string finisherUserNameField;
        
        private string listIdField;
        
        /// <remarks/>
        public System.DateTime StartDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FinishDateTime {
            get {
                return this.finishDateTimeField;
            }
            set {
                this.finishDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BeginerId {
            get {
                return this.beginerIdField;
            }
            set {
                this.beginerIdField = value;
            }
        }
        
        /// <remarks/>
        public string BeginerUserName {
            get {
                return this.beginerUserNameField;
            }
            set {
                this.beginerUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BeginerEMail {
            get {
                return this.beginerEMailField;
            }
            set {
                this.beginerEMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FinisherId {
            get {
                return this.finisherIdField;
            }
            set {
                this.finisherIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FinisherEMail {
            get {
                return this.finisherEMailField;
            }
            set {
                this.finisherEMailField = value;
            }
        }
        
        /// <remarks/>
        public string FinisherUserName {
            get {
                return this.finisherUserNameField;
            }
            set {
                this.finisherUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListId {
            get {
                return this.listIdField;
            }
            set {
                this.listIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itworks24.ru/sisyphus/trellosync")]
    public partial class Nomenclature {
        
        private string nameField;
        
        private string idField;
        
        private string representField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Represent {
            get {
                return this.representField;
            }
            set {
                this.representField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itworks24.ru/sisyphus/trellosync")]
    public partial class Contractor {
        
        private string nameField;
        
        private string idField;
        
        private string eMailField;
        
        private string representField;
        
        private string boardIdField;
        
        private System.Nullable<int> iNNField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        /// <remarks/>
        public string Represent {
            get {
                return this.representField;
            }
            set {
                this.representField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BoardId {
            get {
                return this.boardIdField;
            }
            set {
                this.boardIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://itworks24.ru/sisyphus/trellosync")]
    public partial class Comment {
        
        private object userEMailField;
        
        private string userNameField;
        
        private object textField;
        
        private System.DateTime commentDateTimeField;
        
        /// <remarks/>
        public object UserEMail {
            get {
                return this.userEMailField;
            }
            set {
                this.userEMailField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public object Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CommentDateTime {
            get {
                return this.commentDateTimeField;
            }
            set {
                this.commentDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void AddCardHistoryCompletedEventHandler(object sender, AddCardHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCardHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCardHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ErrorRepresent {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetСontractorsCompletedEventHandler(object sender, GetСontractorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetСontractorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetСontractorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Contractor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Contractor[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ErrorRepresent {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetNomenclatureCompletedEventHandler(object sender, GetNomenclatureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNomenclatureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNomenclatureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Nomenclature[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Nomenclature[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ErrorRepresent {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SetContractorsBoardsCompletedEventHandler(object sender, SetContractorsBoardsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetContractorsBoardsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetContractorsBoardsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ErrorRepresent {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SetContractorBoardCompletedEventHandler(object sender, SetContractorBoardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetContractorBoardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetContractorBoardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ErrorRepresent {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591