//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisyphus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sisyphus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start mail parse.
        ///.
        /// </summary>
        public static string CheckIMAPConnection_ExecuteProcess_ {
            get {
                return ResourceManager.GetString("CheckIMAPConnection_ExecuteProcess_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DKIM and APF tests fails.
        /// </summary>
        public static string CheckIMAPConnection_ExecuteProcess_DKIM_and_APF_tests_fails {
            get {
                return ResourceManager.GetString("CheckIMAPConnection_ExecuteProcess_DKIM_and_APF_tests_fails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DKIM and SPF tests pass.
        /// </summary>
        public static string CheckIMAPConnection_ExecuteProcess_DKIM_and_SPF_tests_pass {
            get {
                return ResourceManager.GetString("CheckIMAPConnection_ExecuteProcess_DKIM_and_SPF_tests_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End mail parse..
        /// </summary>
        public static string CheckIMAPConnection_ExecuteProcess_End_mail_parse_ {
            get {
                return ResourceManager.GetString("CheckIMAPConnection_ExecuteProcess_End_mail_parse_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESSAGE UID {0}, SUBJECT {1}, FROM {2}, {3}.
        /// </summary>
        public static string CheckIMAPConnection_ExecuteProcess_MESSAGE_UID__0___SUBJECT__1___FROM__2____3_ {
            get {
                return ResourceManager.GetString("CheckIMAPConnection_ExecuteProcess_MESSAGE_UID__0___SUBJECT__1___FROM__2____3_", resourceCulture);
            }
        }
    }
}
