//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class visitItem
{

    private visitItemGuests guestsField;

    private orderItem[] ordersField;

    private string visitIDField;

    private string guidField;

    private bool finishedField;

    private bool finishedFieldSpecified;

    private string guestsCountField;

    private string persistentCommentField;

    private string nonPersistentCommentField;

    private string guestTypeIDField;

    private string guestTypeCodeField;

    private string guestTypeNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public visitItemGuests Guests
    {
        get
        {
            return this.guestsField;
        }
        set
        {
            this.guestsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Order", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public orderItem[] Orders
    {
        get
        {
            return this.ordersField;
        }
        set
        {
            this.ordersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string VisitID
    {
        get
        {
            return this.visitIDField;
        }
        set
        {
            this.visitIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string guid
    {
        get
        {
            return this.guidField;
        }
        set
        {
            this.guidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Finished
    {
        get
        {
            return this.finishedField;
        }
        set
        {
            this.finishedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FinishedSpecified
    {
        get
        {
            return this.finishedFieldSpecified;
        }
        set
        {
            this.finishedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string GuestsCount
    {
        get
        {
            return this.guestsCountField;
        }
        set
        {
            this.guestsCountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string PersistentComment
    {
        get
        {
            return this.persistentCommentField;
        }
        set
        {
            this.persistentCommentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string NonPersistentComment
    {
        get
        {
            return this.nonPersistentCommentField;
        }
        set
        {
            this.nonPersistentCommentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string GuestTypeID
    {
        get
        {
            return this.guestTypeIDField;
        }
        set
        {
            this.guestTypeIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string GuestTypeCode
    {
        get
        {
            return this.guestTypeCodeField;
        }
        set
        {
            this.guestTypeCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string GuestTypeName
    {
        get
        {
            return this.guestTypeNameField;
        }
        set
        {
            this.guestTypeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class visitItemGuests
{

    private guestItem[] guestField;

    private int countField;

    private bool countFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Guest", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public guestItem[] Guest
    {
        get
        {
            return this.guestField;
        }
        set
        {
            this.guestField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int count
    {
        get
        {
            return this.countField;
        }
        set
        {
            this.countField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool countSpecified
    {
        get
        {
            return this.countFieldSpecified;
        }
        set
        {
            this.countFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class guestItem
{

    private string guestLabelField;

    private bool closedField;

    private bool closedFieldSpecified;

    private string cardCodeField;

    private string intfIDField;

    private string intfCodeField;

    private string intfNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
    public string GuestLabel
    {
        get
        {
            return this.guestLabelField;
        }
        set
        {
            this.guestLabelField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool closed
    {
        get
        {
            return this.closedField;
        }
        set
        {
            this.closedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool closedSpecified
    {
        get
        {
            return this.closedFieldSpecified;
        }
        set
        {
            this.closedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string CardCode
    {
        get
        {
            return this.cardCodeField;
        }
        set
        {
            this.cardCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string IntfID
    {
        get
        {
            return this.intfIDField;
        }
        set
        {
            this.intfIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string IntfCode
    {
        get
        {
            return this.intfCodeField;
        }
        set
        {
            this.intfCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string IntfName
    {
        get
        {
            return this.intfNameField;
        }
        set
        {
            this.intfNameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resEmployeeItem))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class resRefItem
{

    private string idField;

    private string codeField;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class resEmployeeItem : resRefItem
{

    private resRefItem roleField;

    /// <remarks/>
    public resRefItem Role
    {
        get
        {
            return this.roleField;
        }
        set
        {
            this.roleField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(checkItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(payItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(prepayItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(dishAncestor))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(comboComponent))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(dishItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resDishItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(comboItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resComboItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(consumItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(voidItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(discountItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(modiItem))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class refItem
{

    private string idField;

    private string codeField;

    private string guidField;

    private System.Xml.XmlAttribute[] anyAttrField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string guid
    {
        get
        {
            return this.guidField;
        }
        set
        {
            this.guidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr
    {
        get
        {
            return this.anyAttrField;
        }
        set
        {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(payItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(prepayItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(dishAncestor))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(comboComponent))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(dishItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resDishItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(comboItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resComboItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(consumItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(voidItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(discountItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(modiItem))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class checkItem : refItem
{

    private string uniField;

    private string line_guidField;

    private int stateField;

    private bool stateFieldSpecified;

    private System.Xml.XmlAttribute[] anyAttr1Field;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string uni
    {
        get
        {
            return this.uniField;
        }
        set
        {
            this.uniField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string line_guid
    {
        get
        {
            return this.line_guidField;
        }
        set
        {
            this.line_guidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stateSpecified
    {
        get
        {
            return this.stateFieldSpecified;
        }
        set
        {
            this.stateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr1
    {
        get
        {
            return this.anyAttr1Field;
        }
        set
        {
            this.anyAttr1Field = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(prepayItem))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class payItem : checkItem
{

    private refItem interfaceField;

    private int amountField;

    private string cardCodeField;

    private string extTransactionInfoField;

    private int transactionStatusField;

    private bool transactionStatusFieldSpecified;

    private string seatField;

    private bool deletedField;

    private bool deletedFieldSpecified;

    public payItem()
    {
        this.seatField = "0";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public refItem Interface
    {
        get
        {
            return this.interfaceField;
        }
        set
        {
            this.interfaceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string cardCode
    {
        get
        {
            return this.cardCodeField;
        }
        set
        {
            this.cardCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string extTransactionInfo
    {
        get
        {
            return this.extTransactionInfoField;
        }
        set
        {
            this.extTransactionInfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int TransactionStatus
    {
        get
        {
            return this.transactionStatusField;
        }
        set
        {
            this.transactionStatusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransactionStatusSpecified
    {
        get
        {
            return this.transactionStatusFieldSpecified;
        }
        set
        {
            this.transactionStatusFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string seat
    {
        get
        {
            return this.seatField;
        }
        set
        {
            this.seatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool deleted
    {
        get
        {
            return this.deletedField;
        }
        set
        {
            this.deletedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool deletedSpecified
    {
        get
        {
            return this.deletedFieldSpecified;
        }
        set
        {
            this.deletedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class prepayItem : payItem
{

    private refItem reasonField;

    private bool promisedField;

    private bool promisedFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public refItem Reason
    {
        get
        {
            return this.reasonField;
        }
        set
        {
            this.reasonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool promised
    {
        get
        {
            return this.promisedField;
        }
        set
        {
            this.promisedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool promisedSpecified
    {
        get
        {
            return this.promisedFieldSpecified;
        }
        set
        {
            this.promisedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(comboComponent))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(dishItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resDishItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(comboItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resComboItem))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class dishAncestor : checkItem
{

    private checkItem[] itemsField;

    private string priceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Consum", typeof(consumItem), Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("Discount", typeof(discountItem), Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("Modi", typeof(modiItem), Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("Void", typeof(voidItem), Order = 0)]
    public checkItem[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class consumItem : checkItem
{

    private refItem authorField;

    private int amountField;

    private bool amountFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public refItem Author
    {
        get
        {
            return this.authorField;
        }
        set
        {
            this.authorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool amountSpecified
    {
        get
        {
            return this.amountFieldSpecified;
        }
        set
        {
            this.amountFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class discountItem : checkItem
{

    private refItem interfaceField;

    private refItem bonusTypeField;

    private int amountField;

    private bool amountFieldSpecified;

    private int maxamountField;

    private bool maxamountFieldSpecified;

    private string seatField;

    private string cardCodeField;

    private bool deletedField;

    private bool deletedFieldSpecified;

    public discountItem()
    {
        this.seatField = "0";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public refItem Interface
    {
        get
        {
            return this.interfaceField;
        }
        set
        {
            this.interfaceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public refItem BonusType
    {
        get
        {
            return this.bonusTypeField;
        }
        set
        {
            this.bonusTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool amountSpecified
    {
        get
        {
            return this.amountFieldSpecified;
        }
        set
        {
            this.amountFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int maxamount
    {
        get
        {
            return this.maxamountField;
        }
        set
        {
            this.maxamountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxamountSpecified
    {
        get
        {
            return this.maxamountFieldSpecified;
        }
        set
        {
            this.maxamountFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string seat
    {
        get
        {
            return this.seatField;
        }
        set
        {
            this.seatField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string cardCode
    {
        get
        {
            return this.cardCodeField;
        }
        set
        {
            this.cardCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool deleted
    {
        get
        {
            return this.deletedField;
        }
        set
        {
            this.deletedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool deletedSpecified
    {
        get
        {
            return this.deletedFieldSpecified;
        }
        set
        {
            this.deletedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class modiItem : checkItem
{

    private int priceField;

    private bool priceFieldSpecified;

    private string countField;

    private string openNameField;

    private bool isDefaultField;

    public modiItem()
    {
        this.countField = "1";
        this.isDefaultField = true;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool priceSpecified
    {
        get
        {
            return this.priceFieldSpecified;
        }
        set
        {
            this.priceFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string count
    {
        get
        {
            return this.countField;
        }
        set
        {
            this.countField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string openName
    {
        get
        {
            return this.openNameField;
        }
        set
        {
            this.openNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool isDefault
    {
        get
        {
            return this.isDefaultField;
        }
        set
        {
            this.isDefaultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class voidItem : checkItem
{

    private refItem authorField;

    private System.DateTime dateTimeField;

    private bool dateTimeFieldSpecified;

    private int quantityField;

    private int amountField;

    private bool amountFieldSpecified;

    private string openNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public refItem Author
    {
        get
        {
            return this.authorField;
        }
        set
        {
            this.authorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime dateTime
    {
        get
        {
            return this.dateTimeField;
        }
        set
        {
            this.dateTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateTimeSpecified
    {
        get
        {
            return this.dateTimeFieldSpecified;
        }
        set
        {
            this.dateTimeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int quantity
    {
        get
        {
            return this.quantityField;
        }
        set
        {
            this.quantityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool amountSpecified
    {
        get
        {
            return this.amountFieldSpecified;
        }
        set
        {
            this.amountFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string openName
    {
        get
        {
            return this.openNameField;
        }
        set
        {
            this.openNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class comboComponent : dishAncestor
{

    private refItem comboModiField;

    private string countField;

    private bool isDefaultField;

    public comboComponent()
    {
        this.countField = "1";
        this.isDefaultField = true;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public refItem ComboModi
    {
        get
        {
            return this.comboModiField;
        }
        set
        {
            this.comboModiField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string count
    {
        get
        {
            return this.countField;
        }
        set
        {
            this.countField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool isDefault
    {
        get
        {
            return this.isDefaultField;
        }
        set
        {
            this.isDefaultField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resDishItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(comboItem))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resComboItem))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class dishItem : dishAncestor
{

    private int quantityField;

    private int srcQuantityField;

    private bool srcQuantityFieldSpecified;

    private string seatField;

    public dishItem()
    {
        this.seatField = "0";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int quantity
    {
        get
        {
            return this.quantityField;
        }
        set
        {
            this.quantityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int srcQuantity
    {
        get
        {
            return this.srcQuantityField;
        }
        set
        {
            this.srcQuantityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool srcQuantitySpecified
    {
        get
        {
            return this.srcQuantityFieldSpecified;
        }
        set
        {
            this.srcQuantityFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string seat
    {
        get
        {
            return this.seatField;
        }
        set
        {
            this.seatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class resDishItem : dishItem
{

    private int amountField;

    private bool amountFieldSpecified;

    private KDSStateType kdsstateField;

    private bool newField;

    public resDishItem()
    {
        this.kdsstateField = KDSStateType.Item;
        this.newField = false;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool amountSpecified
    {
        get
        {
            return this.amountFieldSpecified;
        }
        set
        {
            this.amountFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(KDSStateType.Item)]
    public KDSStateType kdsstate
    {
        get
        {
            return this.kdsstateField;
        }
        set
        {
            this.kdsstateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool @new
    {
        get
        {
            return this.newField;
        }
        set
        {
            this.newField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
public enum KDSStateType
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,

    /// <remarks/>
    sent,

    /// <remarks/>
    started,

    /// <remarks/>
    ready,

    /// <remarks/>
    taken,

    /// <remarks/>
    collect,

    /// <remarks/>
    collected,

    /// <remarks/>
    startpark,

    /// <remarks/>
    endpark,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resComboItem))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class comboItem : dishItem
{

    private modiItem modiField;

    private comboComponent[] componentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public modiItem Modi
    {
        get
        {
            return this.modiField;
        }
        set
        {
            this.modiField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Component", Order = 1)]
    public comboComponent[] Component
    {
        get
        {
            return this.componentField;
        }
        set
        {
            this.componentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class resComboItem : comboItem
{

    private KDSStateType kdsstateField;

    private int amountField;

    private bool amountFieldSpecified;

    private bool newField;

    private bool newFieldSpecified;

    public resComboItem()
    {
        this.kdsstateField = KDSStateType.Item;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(KDSStateType.Item)]
    public KDSStateType kdsstate
    {
        get
        {
            return this.kdsstateField;
        }
        set
        {
            this.kdsstateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool amountSpecified
    {
        get
        {
            return this.amountFieldSpecified;
        }
        set
        {
            this.amountFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool @new
    {
        get
        {
            return this.newField;
        }
        set
        {
            this.newField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool newSpecified
    {
        get
        {
            return this.newFieldSpecified;
        }
        set
        {
            this.newFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class orderItem
{

    private orderItemExternalID[] externalIDField;

    private refItem[] extraTablesField;

    private string orderIDField;

    private string versionField;

    private int crc32Field;

    private string guidField;

    private bool dontcheckLicenseField;

    private bool dontcheckLicenseFieldSpecified;

    private string promoCodeField;

    private bool lockedField;

    private bool lockedFieldSpecified;

    private string urlField;

    private string orderNameField;

    private string orderSumField;

    private string toPaySumField;

    private string prepaySumField;

    private string promisedSumField;

    private string priceListSumField;

    private string totalPiecesField;

    private System.DateTime createTimeField;

    private bool createTimeFieldSpecified;

    private System.DateTime finishTimeField;

    private bool finishTimeFieldSpecified;

    private bool finishedField;

    private bool finishedFieldSpecified;

    private bool billField;

    private bool billFieldSpecified;

    private bool receiptErrorField;

    private bool receiptErrorFieldSpecified;

    private bool dessertField;

    private bool dessertFieldSpecified;

    private bool bySeatsField;

    private bool bySeatsFieldSpecified;

    private bool readyExistsField;

    private bool readyExistsFieldSpecified;

    private bool weightNeededField;

    private bool weightNeededFieldSpecified;

    private System.DateTime billTimeField;

    private bool billTimeFieldSpecified;

    private System.DateTime dessertTimeField;

    private bool dessertTimeFieldSpecified;

    private string tableIDField;

    private string tableCodeField;

    private string tableNameField;

    private string waiterIDField;

    private string waiterCodeField;

    private string waiterNameField;

    private string orderCategIDField;

    private string orderCategCodeField;

    private string orderCategNameField;

    private string orderTypeIDField;

    private string orderTypeCodeField;

    private string orderTypeNameField;

    private string defaulterIDField;

    private string defaulterCodeField;

    private string defaulterNameField;

    public orderItem()
    {
        this.prepaySumField = "0";
        this.promisedSumField = "0";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExternalID", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public orderItemExternalID[] ExternalID
    {
        get
        {
            return this.externalIDField;
        }
        set
        {
            this.externalIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public refItem[] ExtraTables
    {
        get
        {
            return this.extraTablesField;
        }
        set
        {
            this.extraTablesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
    public string OrderID
    {
        get
        {
            return this.orderIDField;
        }
        set
        {
            this.orderIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int crc32
    {
        get
        {
            return this.crc32Field;
        }
        set
        {
            this.crc32Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string guid
    {
        get
        {
            return this.guidField;
        }
        set
        {
            this.guidField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool dontcheckLicense
    {
        get
        {
            return this.dontcheckLicenseField;
        }
        set
        {
            this.dontcheckLicenseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dontcheckLicenseSpecified
    {
        get
        {
            return this.dontcheckLicenseFieldSpecified;
        }
        set
        {
            this.dontcheckLicenseFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string promoCode
    {
        get
        {
            return this.promoCodeField;
        }
        set
        {
            this.promoCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool locked
    {
        get
        {
            return this.lockedField;
        }
        set
        {
            this.lockedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lockedSpecified
    {
        get
        {
            return this.lockedFieldSpecified;
        }
        set
        {
            this.lockedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string OrderName
    {
        get
        {
            return this.orderNameField;
        }
        set
        {
            this.orderNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string OrderSum
    {
        get
        {
            return this.orderSumField;
        }
        set
        {
            this.orderSumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string ToPaySum
    {
        get
        {
            return this.toPaySumField;
        }
        set
        {
            this.toPaySumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string PrepaySum
    {
        get
        {
            return this.prepaySumField;
        }
        set
        {
            this.prepaySumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    [System.ComponentModel.DefaultValueAttribute("0")]
    public string PromisedSum
    {
        get
        {
            return this.promisedSumField;
        }
        set
        {
            this.promisedSumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string PriceListSum
    {
        get
        {
            return this.priceListSumField;
        }
        set
        {
            this.priceListSumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string TotalPieces
    {
        get
        {
            return this.totalPiecesField;
        }
        set
        {
            this.totalPiecesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime CreateTime
    {
        get
        {
            return this.createTimeField;
        }
        set
        {
            this.createTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateTimeSpecified
    {
        get
        {
            return this.createTimeFieldSpecified;
        }
        set
        {
            this.createTimeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime FinishTime
    {
        get
        {
            return this.finishTimeField;
        }
        set
        {
            this.finishTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FinishTimeSpecified
    {
        get
        {
            return this.finishTimeFieldSpecified;
        }
        set
        {
            this.finishTimeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Finished
    {
        get
        {
            return this.finishedField;
        }
        set
        {
            this.finishedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FinishedSpecified
    {
        get
        {
            return this.finishedFieldSpecified;
        }
        set
        {
            this.finishedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Bill
    {
        get
        {
            return this.billField;
        }
        set
        {
            this.billField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BillSpecified
    {
        get
        {
            return this.billFieldSpecified;
        }
        set
        {
            this.billFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ReceiptError
    {
        get
        {
            return this.receiptErrorField;
        }
        set
        {
            this.receiptErrorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReceiptErrorSpecified
    {
        get
        {
            return this.receiptErrorFieldSpecified;
        }
        set
        {
            this.receiptErrorFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Dessert
    {
        get
        {
            return this.dessertField;
        }
        set
        {
            this.dessertField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DessertSpecified
    {
        get
        {
            return this.dessertFieldSpecified;
        }
        set
        {
            this.dessertFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool bySeats
    {
        get
        {
            return this.bySeatsField;
        }
        set
        {
            this.bySeatsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bySeatsSpecified
    {
        get
        {
            return this.bySeatsFieldSpecified;
        }
        set
        {
            this.bySeatsFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ReadyExists
    {
        get
        {
            return this.readyExistsField;
        }
        set
        {
            this.readyExistsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReadyExistsSpecified
    {
        get
        {
            return this.readyExistsFieldSpecified;
        }
        set
        {
            this.readyExistsFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool WeightNeeded
    {
        get
        {
            return this.weightNeededField;
        }
        set
        {
            this.weightNeededField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WeightNeededSpecified
    {
        get
        {
            return this.weightNeededFieldSpecified;
        }
        set
        {
            this.weightNeededFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime BillTime
    {
        get
        {
            return this.billTimeField;
        }
        set
        {
            this.billTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BillTimeSpecified
    {
        get
        {
            return this.billTimeFieldSpecified;
        }
        set
        {
            this.billTimeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime DessertTime
    {
        get
        {
            return this.dessertTimeField;
        }
        set
        {
            this.dessertTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DessertTimeSpecified
    {
        get
        {
            return this.dessertTimeFieldSpecified;
        }
        set
        {
            this.dessertTimeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string TableID
    {
        get
        {
            return this.tableIDField;
        }
        set
        {
            this.tableIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string TableCode
    {
        get
        {
            return this.tableCodeField;
        }
        set
        {
            this.tableCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string TableName
    {
        get
        {
            return this.tableNameField;
        }
        set
        {
            this.tableNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string WaiterID
    {
        get
        {
            return this.waiterIDField;
        }
        set
        {
            this.waiterIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string WaiterCode
    {
        get
        {
            return this.waiterCodeField;
        }
        set
        {
            this.waiterCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string WaiterName
    {
        get
        {
            return this.waiterNameField;
        }
        set
        {
            this.waiterNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string OrderCategID
    {
        get
        {
            return this.orderCategIDField;
        }
        set
        {
            this.orderCategIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string OrderCategCode
    {
        get
        {
            return this.orderCategCodeField;
        }
        set
        {
            this.orderCategCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string OrderCategName
    {
        get
        {
            return this.orderCategNameField;
        }
        set
        {
            this.orderCategNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string OrderTypeID
    {
        get
        {
            return this.orderTypeIDField;
        }
        set
        {
            this.orderTypeIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string OrderTypeCode
    {
        get
        {
            return this.orderTypeCodeField;
        }
        set
        {
            this.orderTypeCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string OrderTypeName
    {
        get
        {
            return this.orderTypeNameField;
        }
        set
        {
            this.orderTypeNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string DefaulterID
    {
        get
        {
            return this.defaulterIDField;
        }
        set
        {
            this.defaulterIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string DefaulterCode
    {
        get
        {
            return this.defaulterCodeField;
        }
        set
        {
            this.defaulterCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string DefaulterName
    {
        get
        {
            return this.defaulterNameField;
        }
        set
        {
            this.defaulterNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class orderItemExternalID
{

    private string extSourceField;

    private string extIDField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
    public string ExtSource
    {
        get
        {
            return this.extSourceField;
        }
        set
        {
            this.extSourceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string ExtID
    {
        get
        {
            return this.extIDField;
        }
        set
        {
            this.extIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RK7QueryResult
{

    private string serverVersionField;

    private string xmlVersionField;

    private string netNameField;

    private string cMDField;

    private RK7QueryResultStatus statusField;

    private string rK7ErrorNField;

    private string errorTextField;

    private string workTimeField;

    private System.DateTime dateTimeField;

    private string processedField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string ServerVersion
    {
        get
        {
            return this.serverVersionField;
        }
        set
        {
            this.serverVersionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
    public string XmlVersion
    {
        get
        {
            return this.xmlVersionField;
        }
        set
        {
            this.xmlVersionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NetName
    {
        get
        {
            return this.netNameField;
        }
        set
        {
            this.netNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
    public string CMD
    {
        get
        {
            return this.cMDField;
        }
        set
        {
            this.cMDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public RK7QueryResultStatus Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
    public string RK7ErrorN
    {
        get
        {
            return this.rK7ErrorNField;
        }
        set
        {
            this.rK7ErrorNField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "normalizedString")]
    public string ErrorText
    {
        get
        {
            return this.errorTextField;
        }
        set
        {
            this.errorTextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string WorkTime
    {
        get
        {
            return this.workTimeField;
        }
        set
        {
            this.workTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime DateTime
    {
        get
        {
            return this.dateTimeField;
        }
        set
        {
            this.dateTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string Processed
    {
        get
        {
            return this.processedField;
        }
        set
        {
            this.processedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum RK7QueryResultStatus
{

    /// <remarks/>
    Ok,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("No changes")]
    Nochanges,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Execution Started")]
    ExecutionStarted,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Query Parse Error")]
    QueryParseError,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Bad Query Parameters")]
    BadQueryParameters,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Query Executing Error")]
    QueryExecutingError,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Result Writing Error")]
    ResultWritingError,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false, ElementName = "RK7QueryResult")]
public partial class GetOrderListQueryResult : RK7QueryResult
{

    private visitItem[] visitField;

    private string lastversionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Visit", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public visitItem[] Visit
    {
        get
        {
            return this.visitField;
        }
        set
        {
            this.visitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string lastversion
    {
        get
        {
            return this.lastversionField;
        }
        set
        {
            this.lastversionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false, ElementName = "RK7QueryResult")]
public partial class GetWaiterListQueryResult : RK7QueryResult
{

    private GetWaiterListQueryResultWaiter[] waitersField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("waiter", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public GetWaiterListQueryResultWaiter[] Waiters
    {
        get
        {
            return this.waitersField;
        }
        set
        {
            this.waitersField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetWaiterListQueryResultWaiter
{

    private resRefItem drawerField;

    private resRefItem[] stationField;

    private string idField;

    private string codeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resRefItem Drawer
    {
        get
        {
            return this.drawerField;
        }
        set
        {
            this.drawerField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Station", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public resRefItem[] Station
    {
        get
        {
            return this.stationField;
        }
        set
        {
            this.stationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
    public string Code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("RK7QueryResult", Namespace = "", IsNullable = false, ElementName = "RK7QueryResult")]
public partial class GetSystemInfo2QueryResult : RK7QueryResult
{

    private RK7QueryResultSystemInfo systemInfoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RK7QueryResultSystemInfo SystemInfo
    {
        get
        {
            return this.systemInfoField;
        }
        set
        {
            this.systemInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class RK7QueryResultSystemInfo
{

    private refItem cashField;

    private refItem cashGroupField;

    private refItem restaurantField;

    private refItem waiterField;

    private CommonShift commonShiftField;

    private int processIDField;

    private bool processIDFieldSpecified;

    private int restCodeField;

    private bool restCodeFieldSpecified;

    private System.DateTime uptimeField;

    private bool uptimeFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public refItem Cash
    {
        get
        {
            return this.cashField;
        }
        set
        {
            this.cashField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public refItem CashGroup
    {
        get
        {
            return this.cashGroupField;
        }
        set
        {
            this.cashGroupField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public refItem Restaurant
    {
        get
        {
            return this.restaurantField;
        }
        set
        {
            this.restaurantField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public refItem Waiter
    {
        get
        {
            return this.waiterField;
        }
        set
        {
            this.waiterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public CommonShift CommonShift
    {
        get
        {
            return this.commonShiftField;
        }
        set
        {
            this.commonShiftField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ProcessID
    {
        get
        {
            return this.processIDField;
        }
        set
        {
            this.processIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ProcessIDSpecified
    {
        get
        {
            return this.processIDFieldSpecified;
        }
        set
        {
            this.processIDFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int RestCode
    {
        get
        {
            return this.restCodeField;
        }
        set
        {
            this.restCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RestCodeSpecified
    {
        get
        {
            return this.restCodeFieldSpecified;
        }
        set
        {
            this.restCodeFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime uptime
    {
        get
        {
            return this.uptimeField;
        }
        set
        {
            this.uptimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool uptimeSpecified
    {
        get
        {
            return this.uptimeFieldSpecified;
        }
        set
        {
            this.uptimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CommonShift
{

    private System.DateTime shiftDateField;

    private bool shiftDateFieldSpecified;

    private int shiftNumField;

    private bool shiftNumFieldSpecified;

    private System.DateTime shiftStartTimeField;

    private bool shiftStartTimeFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime ShiftDate
    {
        get
        {
            return this.shiftDateField;
        }
        set
        {
            this.shiftDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShiftDateSpecified
    {
        get
        {
            return this.shiftDateFieldSpecified;
        }
        set
        {
            this.shiftDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int ShiftNum
    {
        get
        {
            return this.shiftNumField;
        }
        set
        {
            this.shiftNumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShiftNumSpecified
    {
        get
        {
            return this.shiftNumFieldSpecified;
        }
        set
        {
            this.shiftNumFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime ShiftStartTime
    {
        get
        {
            return this.shiftStartTimeField;
        }
        set
        {
            this.shiftStartTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShiftStartTimeSpecified
    {
        get
        {
            return this.shiftStartTimeFieldSpecified;
        }
        set
        {
            this.shiftStartTimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = false)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class GetOrderListCMD : RK7QueryRK7CMD
{

    private refItem waiterField;

    private refItem tableField;

    private string cMDField;

    private string lastversionField;

    private bool onlyOpenedField;

    private bool onlyOpenedFieldSpecified;

    private bool needIdentsField;

    private bool needCodesField;

    private int needNamesField;

    public GetOrderListCMD()
    {
        this.cMDField = "GetOrderList";
        this.needIdentsField = true;
        this.needCodesField = true;
        this.needNamesField = 1;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public refItem Waiter
    {
        get
        {
            return this.waiterField;
        }
        set
        {
            this.waiterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public refItem Table
    {
        get
        {
            return this.tableField;
        }
        set
        {
            this.tableField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CMD
    {
        get
        {
            return this.cMDField;
        }
        set
        {
            this.cMDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
    public string lastversion
    {
        get
        {
            return this.lastversionField;
        }
        set
        {
            this.lastversionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool onlyOpened
    {
        get
        {
            return this.onlyOpenedField;
        }
        set
        {
            this.onlyOpenedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool onlyOpenedSpecified
    {
        get
        {
            return this.onlyOpenedFieldSpecified;
        }
        set
        {
            this.onlyOpenedFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool needIdents
    {
        get
        {
            return this.needIdentsField;
        }
        set
        {
            this.needIdentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool needCodes
    {
        get
        {
            return this.needCodesField;
        }
        set
        {
            this.needCodesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public int needNames
    {
        get
        {
            return this.needNamesField;
        }
        set
        {
            this.needNamesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = false)]
public partial class GetWaiterListCMD : RK7QueryRK7CMD
{

    private refItem tableField;

    private string cMDField;

    private bool registeredOnlyField;

    private bool registeredOnlyFieldSpecified;

    public GetWaiterListCMD()
    {
        this.cMDField = "GetWaiterList";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public refItem Table
    {
        get
        {
            return this.tableField;
        }
        set
        {
            this.tableField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CMD
    {
        get
        {
            return this.cMDField;
        }
        set
        {
            this.cMDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool registeredOnly
    {
        get
        {
            return this.registeredOnlyField;
        }
        set
        {
            this.registeredOnlyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool registeredOnlySpecified
    {
        get
        {
            return this.registeredOnlyFieldSpecified;
        }
        set
        {
            this.registeredOnlyFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = false)]
public partial class GetSystemInfo2CMD : RK7QueryRK7CMD
{

    private string cMDField;

    public GetSystemInfo2CMD()
    {
        this.cMDField = "GetSystemInfo2";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CMD
    {
        get
        {
            return this.cMDField;
        }
        set
        {
            this.cMDField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlInclude(typeof(GetWaiterListCMD))]
[XmlInclude(typeof(GetOrderListCMD))]
[XmlInclude(typeof(GetSystemInfo2CMD))]
public abstract class RK7QueryRK7CMD
{

    private string cMDField;

    public RK7QueryRK7CMD()
    {
        this.cMDField = "SystemInfo";
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CMD
    {
        get
        {
            return this.cMDField;
        }
        set
        {
            this.cMDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class RK7Query
{

    private RK7QueryRK7CMD rK7CMDField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RK7QueryRK7CMD RK7CMD
    {
        get
        {
            return this.rK7CMDField;
        }
        set
        {
            this.rK7CMDField = value;
        }
    }
}

