//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANDRIGHTS
    {
        public int BANDEDPROPSRIGHT { get; set; }
        public int IDENT { get; set; }
        public string NAME { get; set; }
        public Nullable<short> INCLUDED { get; set; }
        public Nullable<short> EXCLUDED { get; set; }
        public Nullable<short> BEHAVIOR { get; set; }
        public Nullable<short> CHANGED { get; set; }
        public string RECSTAMP { get; set; }
        public Nullable<short> DBSTATUS { get; set; }
    }
}
