//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKTABLEFIELDS
    {
        public short TABLE { get; set; }
        public short NUMINTABLE { get; set; }
        public string FIELDNAME { get; set; }
        public Nullable<short> SUBTYPE { get; set; }
        public string TYPENAME { get; set; }
        public Nullable<short> AXIS { get; set; }
        public Nullable<short> FLAGS { get; set; }
        public string GROUP { get; set; }
        public string NAME { get; set; }
        public string DESC { get; set; }
        public string RECSTAMP { get; set; }
        public Nullable<short> DBSTATUS { get; set; }
    }
}
