//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASSINFOPROPRESTRICTS
    {
        public int CLASSINFO { get; set; }
        public int PROPIDENT { get; set; }
        public Nullable<int> ITEMIDENT { get; set; }
        public string PROPERTYNAME { get; set; }
        public Nullable<int> USAGEFLAGS { get; set; }
        public Nullable<int> MINPROPVALUE { get; set; }
        public Nullable<int> MAXPROPVALUE { get; set; }
        public string PROPSWARNING { get; set; }
        public string RECSTAMP { get; set; }
        public Nullable<short> DBSTATUS { get; set; }
    }
}
