//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_shcr_CatFoodCost
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> server_guid { get; set; }
        public Nullable<System.DateTime> dateinsert { get; set; }
        public Nullable<System.Guid> ds_guid { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<short> type { get; set; }
        public Nullable<int> Categ_Ref { get; set; }
        public string Categ_Name { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> Brak { get; set; }
        public Nullable<double> Sale { get; set; }
        public Nullable<double> Inv { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> FoodCost { get; set; }
        public Nullable<double> pCost { get; set; }
        public Nullable<double> pBreak { get; set; }
        public Nullable<double> pInv { get; set; }
    }
}
