//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HALLPLANITEMS
    {
        public int HALLPLAN { get; set; }
        public int TABLE { get; set; }
        public Nullable<int> LEFT { get; set; }
        public Nullable<int> TOP { get; set; }
        public Nullable<int> IMAGEINDEX { get; set; }
        public string TEXT { get; set; }
        public Nullable<short> TEXTALIGN { get; set; }
        public Nullable<short> FONTTYPE { get; set; }
        public Nullable<int> TOUCHRANGE { get; set; }
        public Nullable<short> SYNCHRONIZED { get; set; }
        public string RECSTAMP { get; set; }
        public Nullable<short> DBSTATUS { get; set; }
    }
}
