//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERFACEDLL
    {
        public int INTFINST { get; set; }
        public int CASHSERV { get; set; }
        public Nullable<int> LINKSERV { get; set; }
        public string INTFFILE { get; set; }
        public Nullable<int> FILENUM { get; set; }
        public Nullable<int> MODIDENT { get; set; }
        public string RECSTAMP { get; set; }
        public Nullable<short> DBSTATUS { get; set; }
    }
}
