//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KBDLAYOUTKEYS
    {
        public int KBDLAYOUT { get; set; }
        public int KEYIDENT { get; set; }
        public Nullable<short> TRADEOBJECT { get; set; }
        public Nullable<int> OBJECTSIFR { get; set; }
        public Nullable<short> ALTTRADEOBJECT { get; set; }
        public Nullable<int> ALTOBJECTSIFR { get; set; }
        public Nullable<short> MAINCHAR { get; set; }
        public Nullable<short> ALTCHAR { get; set; }
        public Nullable<int> FLAGS { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<short> VISUALMODE { get; set; }
        public Nullable<int> VISUALTYPE_IMAGE { get; set; }
        public Nullable<int> VISUALTYPE_BCOLOR { get; set; }
        public Nullable<short> VISUALTYPE_FONTHEIGHT { get; set; }
        public Nullable<int> VISUALTYPE_TEXTCOLOR { get; set; }
        public Nullable<short> UCSPRESET { get; set; }
        public string RECSTAMP { get; set; }
        public Nullable<short> DBSTATUS { get; set; }
    }
}
