//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OLAPCUBEFIELDS
    {
        public int REPORT { get; set; }
        public int SIFR { get; set; }
        public byte[] LINKPATH { get; set; }
        public string FIELDNAME { get; set; }
        public string SYSFIELDNAME { get; set; }
        public Nullable<short> FLAGS { get; set; }
        public Nullable<short> AXIS { get; set; }
        public string USERNAME { get; set; }
        public string ALTUSERNAME { get; set; }
        public string FIELDFORMAT { get; set; }
        public Nullable<int> POSITION { get; set; }
        public Nullable<double> FACTSCALE { get; set; }
        public Nullable<short> FACTAGGRID { get; set; }
        public Nullable<short> FACTFLAGS { get; set; }
        public Nullable<short> DIMMODIFIER { get; set; }
        public Nullable<short> DIMFLAGS { get; set; }
        public Nullable<short> ISPARAM { get; set; }
        public Nullable<short> FILTERTYPE { get; set; }
        public Nullable<long> FLTMINVALUE { get; set; }
        public Nullable<long> FLTMAXVALUE { get; set; }
        public byte[] FLTVALUELIST { get; set; }
        public string OTHERSOURCETYPE { get; set; }
        public Nullable<short> CALCULATIONTYPE { get; set; }
        public Nullable<int> DEFVALUE { get; set; }
        public byte[] FACTFORMULA { get; set; }
        public Nullable<short> FACTMODIFIER { get; set; }
        public Nullable<int> FACTSRCFACT { get; set; }
        public Nullable<int> FACTNUMERATOR { get; set; }
        public Nullable<int> FACTDENOMINATOR { get; set; }
        public Nullable<int> CONDITIONFIELD { get; set; }
        public string CONDITIONVALUE { get; set; }
        public Nullable<short> FLTDATEMODE { get; set; }
        public Nullable<int> FLTDATEVALUE { get; set; }
        public string DIMDICTIONARY { get; set; }
        public string DIMDICTFIELD { get; set; }
        public string RECSTAMP { get; set; }
        public Nullable<short> DBSTATUS { get; set; }
    }
}
