//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLG_SH4_LINK_STORE
    {
        public string GUIDSTRING { get; set; }
        public string RESTAURANTGUID { get; set; }
        public string CATEGORYGUID { get; set; }
        public string BASEGUID { get; set; }
        public int STORERID { get; set; }
        public Nullable<System.Guid> TRANSACT_GUID { get; set; }
    }
}
