//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLG_IR_WEB_REPORTS_SETTING
    {
        public string GUIDSTRING { get; set; }
        public string SYS_NAME { get; set; }
        public Nullable<short> IR_TYPE { get; set; }
        public string IR_WEB_PLATFORMS_GUID { get; set; }
        public byte[] LAYOUT { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> UCSPRESET { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.Guid> TRANSACT_GUID { get; set; }
        public string USER_GUID { get; set; }
        public string DASHBOARD_GUID { get; set; }
        public string WIDGET_TYPE_GUID { get; set; }
        public string WIDGET_GUID { get; set; }
    }
}
