//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLG_REPORTS_HISTORY
    {
        public string GUIDSTRING { get; set; }
        public string REF_TYPE { get; set; }
        public string REF_OBJECT { get; set; }
        public string VER { get; set; }
        public Nullable<System.DateTime> DATETIME_UPDATE { get; set; }
        public byte[] DESCR { get; set; }
        public string LINK { get; set; }
        public byte[] IR_REP_REDMINE_INFO { get; set; }
        public byte[] IR_REP_REDMINE_INFO_EN { get; set; }
        public string TRANSACT_GUID { get; set; }
    }
}
