//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RKeeperEntities : DbContext
    {
        public RKeeperEntities()
            : base("name=RKeeperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CASHES> CASHES { get; set; }
        public virtual DbSet<CASHGROUPS> CASHGROUPS { get; set; }
        public virtual DbSet<CLASSIFICATORGROUPS> CLASSIFICATORGROUPS { get; set; }
        public virtual DbSet<CLASSINFOS> CLASSINFOS { get; set; }
        public virtual DbSet<CURRENCYTYPES> CURRENCYTYPES { get; set; }
        public virtual DbSet<CURRLINES> CURRLINES { get; set; }
        public virtual DbSet<DISCOUNTS> DISCOUNTS { get; set; }
        public virtual DbSet<DISCPARTS> DISCPARTS { get; set; }
        public virtual DbSet<DISHDISCOUNTS> DISHDISCOUNTS { get; set; }
        public virtual DbSet<DISHGROUPS> DISHGROUPS { get; set; }
        public virtual DbSet<DISHVOIDS> DISHVOIDS { get; set; }
        public virtual DbSet<GLOBALSHIFTS> GLOBALSHIFTS { get; set; }
        public virtual DbSet<GLOBALSHIFTSTATS> GLOBALSHIFTSTATS { get; set; }
        public virtual DbSet<MENUITEMS> MENUITEMS { get; set; }
        public virtual DbSet<ORDERS> ORDERS { get; set; }
        public virtual DbSet<PAYBINDINGS> PAYBINDINGS { get; set; }
        public virtual DbSet<PRINTCHECKS> PRINTCHECKS { get; set; }
        public virtual DbSet<RESTAURANTS> RESTAURANTS { get; set; }
        public virtual DbSet<SESSIONDISHES> SESSIONDISHES { get; set; }
        public virtual DbSet<TEMPGLOBALSHIFTS> TEMPGLOBALSHIFTS { get; set; }
        public virtual DbSet<VISITS> VISITS { get; set; }
        public virtual DbSet<CURRENCIES> CURRENCIES { get; set; }
        public virtual DbSet<TABLES> TABLES { get; set; }
        public virtual DbSet<SALEOBJECTS> SALEOBJECTSSet { get; set; }
    }
}
