//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALEOBJECTS
    {
        public int MIDSERVER { get; set; }
        public int VISIT { get; set; }
        public int DISHUNI { get; set; }
        public Nullable<int> CHARGEUNI { get; set; }
        public Nullable<int> ORDERIDENT { get; set; }
        public Nullable<int> SESSIONUNI { get; set; }
        public int OBJKIND { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public string ALTNAME { get; set; }
        public Nullable<short> RIGHTLVL { get; set; }
        public string TYPEPATH { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<System.DateTime> SALESTERMS_STARTSALE { get; set; }
        public Nullable<System.DateTime> SALESTERMS_STOPSALE { get; set; }
        public Nullable<int> ITAXDISHTYPE { get; set; }
        public Nullable<int> SEAT { get; set; }
        public int EXCLUDEFROMEARNINGS { get; set; }
        public Nullable<decimal> SOURCESUM { get; set; }
        public Nullable<decimal> PAYSUM { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public string GLOBALIDENT { get; set; }
        public Nullable<int> ICREATOR { get; set; }
        public Nullable<int> IAUTHOR { get; set; }
        public Nullable<int> ICREATORROLE { get; set; }
    }
}
