//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_SH4_SHIFTS_FOODCOST
    {
        public System.Guid GUIDSTRING { get; set; }
        public System.Guid BASEGUID { get; set; }
        public Nullable<System.DateTime> UPDATEDATETIME { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> RIDMEASURE { get; set; }
        public string NAMEMEASURE { get; set; }
        public Nullable<int> RIDSTOREHOUSE { get; set; }
        public string NAMESTOREHOUSE { get; set; }
        public Nullable<decimal> WHOLESALESUMNOTAX { get; set; }
        public Nullable<decimal> WHOLESALETAX { get; set; }
        public Nullable<decimal> WHOLESALETAXADD { get; set; }
        public Nullable<decimal> PURCHASESUMNOTAX { get; set; }
        public Nullable<decimal> PURCHASETAX { get; set; }
        public Nullable<decimal> PURCHASETAXADD { get; set; }
        public Nullable<decimal> PURCHASETAXSUM { get; set; }
        public Nullable<decimal> PURCHASETAXADDSUM { get; set; }
        public Nullable<int> ROOTGROUPRID { get; set; }
        public Nullable<System.DateTime> REALUPDATEDATETIME { get; set; }
    }
}
