//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_RK7_SHIFTS_PDSCARDS
    {
        public System.Guid GUIDINTERFACE { get; set; }
        public long ACCOUNTIDENT { get; set; }
        public string CARDCODE { get; set; }
        public string HOLDER { get; set; }
        public Nullable<int> FOLDERID { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> OFFERED { get; set; }
        public Nullable<System.DateTime> EXPIRED { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<short> DELETED { get; set; }
        public Nullable<short> LOCKED { get; set; }
        public Nullable<short> SEIZE { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> LASTUPDATE { get; set; }
    }
}
