//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_RK7_SHIFTS_GPX_ORDERS
    {
        public System.Guid BASEGUID { get; set; }
        public Nullable<System.Guid> POINTGUID { get; set; }
        public Nullable<System.DateTime> POINTDATETIME { get; set; }
        public Nullable<System.DateTime> REALDATETIME { get; set; }
        public Nullable<System.Guid> ORDERGUID { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
