//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_SH4_CURRENCIES
    {
        public string GUIDSTRING { get; set; }
        public string BASEGUID { get; set; }
        public int RID { get; set; }
        public string SYSNAME { get; set; }
        public string BANKCODE { get; set; }
        public string NAME { get; set; }
        public string SHORTNAME { get; set; }
        public string SHORTNAMEPART { get; set; }
        public Nullable<int> CURRENCYOPTION { get; set; }
    }
}
