//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_PR_EMPLOYEEROLES
    {
        public System.Guid GUIDSTRING { get; set; }
        public Nullable<System.Guid> BASEGUID { get; set; }
        public Nullable<System.DateTime> UPDATEDATETIME { get; set; }
        public Nullable<System.DateTime> REALUPDATEDATETIME { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<int> OLDROLEID { get; set; }
        public Nullable<int> NEWROLEID { get; set; }
        public Nullable<int> THEATREID { get; set; }
        public Nullable<int> ROLESTATUS { get; set; }
    }
}
