//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_PR_ROLES
    {
        public System.Guid GUIDSTRING { get; set; }
        public Nullable<System.Guid> BASEGUID { get; set; }
        public Nullable<int> ROLEID { get; set; }
        public string ROLENAME { get; set; }
    }
}
