//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_SH4_SHIFTS_GOODS
    {
        public System.Guid GUIDSTRING { get; set; }
        public System.Guid BASEGUID { get; set; }
        public Nullable<int> RID { get; set; }
        public Nullable<int> PARENTRID { get; set; }
        public string CODESTR { get; set; }
        public string NAME { get; set; }
        public Nullable<int> EXTCODE { get; set; }
    }
}
