//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_RK7_EMPLOYEEROLES
    {
        public System.Guid GUIDSTRING { get; set; }
        public Nullable<System.DateTime> UPDATEDATETIME { get; set; }
        public Nullable<System.Guid> RESTAURANTGUID { get; set; }
        public Nullable<System.Guid> EMPLOYEEGUID { get; set; }
        public Nullable<System.Guid> ROLEGUID { get; set; }
        public Nullable<int> ROLESTATUS { get; set; }
    }
}
