//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_RK7_SHIFTS_PDSFOLDERS
    {
        public System.Guid GUIDINTERFACE { get; set; }
        public int ID { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> DELETED { get; set; }
        public Nullable<System.DateTime> LASTUPDATE { get; set; }
    }
}
