//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_RK7_SHIFTS_CECKSUM
    {
        public System.Guid GUIDSTRING { get; set; }
        public Nullable<int> VALID { get; set; }
        public Nullable<System.DateTime> CREATEDATETIME { get; set; }
        public string AG_VER { get; set; }
        public byte[] CECKSUM { get; set; }
    }
}
