//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RKeeperReporter.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRK7CUBEVIEW2009
    {
        public string TARIFF { get; set; }
        public string DETAIL { get; set; }
        public Nullable<double> DURATION { get; set; }
        public string DEVICE { get; set; }
        public string NETNAME { get; set; }
        public int SHIFTNUM { get; set; }
        public string ORDERNAME { get; set; }
        public string TABLE { get; set; }
        public string RESTAURANTNAME { get; set; }
        public Nullable<System.DateTime> TARIFFSTARTTIME { get; set; }
        public Nullable<System.DateTime> TARIFFENDTIME { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<decimal> PAYSUM { get; set; }
        public Nullable<System.DateTime> TIMELIMIT { get; set; }
        public Nullable<decimal> MONEYLIMIT { get; set; }
        public Nullable<short> REBOOTING { get; set; }
        public Nullable<double> QUANTITY { get; set; }
        public string WAITER { get; set; }
        public string MAINWAITER { get; set; }
        public Nullable<decimal> PRICESUM { get; set; }
        public string STATUS { get; set; }
        public string F00000026 { get; set; }
        public string F0000002D { get; set; }
        public string F0000002E { get; set; }
        public string F00000030 { get; set; }
        public string F00000031 { get; set; }
    }
}
